### PR TITLE
Fix download count to avoid ramdom fail on search_test

### LINKED ISSUE #1497: Spec on test/integration/search_test.rb randomly failing
```
  1) Failure:                                                                                                       
SearchTest#test_params_has_non_white_listed_keys [test/integration/search_test.rb:60]:                              
Expected false to be truthy.
```

cf https://travis-ci.org/rubygems/rubygems.org/jobs/175365149#L1131

### PR DESCRIPTION
**Pull request by spk**
ref c052833efadd62d855333fd7e2028d4e8b58f53c
see https://github.com/spk/rubygems.org/blob/c346b910db404bad1ff209266e4ebd740a5a22b0/app/models/concerns/rubygem_searchable.rb#L138

Fix #1497

### CODE REVIEW

File: test/integration/search_test.rb [hunk 1]
```diff
@@ -50,11 +50,16 @@ class SearchTest < SystemTest
     end
   end
 
-  setup { Rubygem.per_page = 2 }
+  setup do
+    3.times do |i|
+      rubygem = create(:rubygem, name: "ruby#{i}", number: "1.#{i}.0")
```
Comment (segiddins) [inline test/integration/search_test.rb]: is changing the `number` necessary?

Comment (sonalkr132) [inline test/integration/search_test.rb]: `number` creates corresponding version. Our query condition has [`versions.indexed`](https://github.com/spk/rubygems.org/blob/c346b910db404bad1ff209266e4ebd740a5a22b0/app/models/concerns/rubygem_searchable.rb#L127) and without version response will always be empty.

I would suggest not to use `number: "1.#{i}.0"` and let it be `number: "1.0.0"`. Someone may try to read into need of *different* version number when there is none.

Comment (spk) [inline test/integration/search_test.rb]: Yes its useless that was my first guess but I forget to remove it

**Comment by spk** [comment]
@segiddins @sonalkr132 updated and added 9703fe95dc9c5e161a4bff4e92b501115e5b9d01
Cheers

**Comment by segiddins** [comment]
@homu r+
