### PR TITLE
fix by_downloads scope to use new gem_downloads table

### LINKED ISSUE #947: Stats page shows out of date top ten gems
The code that selects the top ten gems on the stats page is querying postgres instead of reds. To get the actual top ten gems, you need code that looks something like this:

```ruby
counts = {}
names = Rubygem.pluck(:name)
names.in_groups_of(100).each do |g|
  counts = Redis.current.multi do |r|
    g.each do |n|
      r.get Download.rubygem_key(n)
    end
  end
  g.zip(counts).each{|n,c| counts[n] = c }
end
counts.sort_by{|x| -x.last.to_i }.first(10)
```

### PR DESCRIPTION
**Pull request by dwradcliffe**
This should fix the stats page sort problem.

Fixes #947

review: @arthurnn

### CODE REVIEW

**Comment by kbrock** [comment]
nice. couldn't be any simpler

**Comment by arthurnn** [comment]
Hey, @dwradcliffe did a few commits: 
- Remove the sort in memory, which is not necassary anymore
- Removed a n+1 on the gem_download load
- Added the index we discussed.

This is good to go I would say 👍

File: db/migrate/20160329184508_create_gem_download_count_index.rb [hunk 1]
```diff
@@ -0,0 +1,5 @@
+class CreateGemDownloadCountIndex < ActiveRecord::Migration
+  def change
+    add_index :gem_downloads, [:version_id, :rubygem_id, :count]
```
Comment (kbrock) [inline db/migrate/20160329184508_create_gem_download_count_index.rb]: - Having `count` will avoid a data page hit. Which is good.
- But since `count` will be changing a lot, the index will be changing a lot. And potentially render the table statistics invalid. So the index would not be very effective, and the data page hit may actually be quicker than dealing with a stale index.
- The `count` column may slow down updates as well.
- `version_id` is almost always be `0` - which is not good at the front of an index. Putting values that are the most different at the front makes for better data distribution (You can challenge this. this may no longer be valid) And yes, you can only use indexes from left to right, so this rule of thumb is not always applicable.
- Making the index `where version_id = 0` would probably be your best bet. (not `schema.rb` friendly - in rails discussions) - but in terms of postgres - it makes a BIG difference. especially for a query such as this.

e.g.:
```sql
create index gem_downloads_rubygem_id on gem_downloads(rubygem_id) where version_id=0
```

Comment (kbrock) [inline db/migrate/20160329184508_create_gem_download_count_index.rb]: hmm. wonder why I was thinking that `version_id: 0` was in the code. Can't find it so ignore the `version_id` being `0` comment.

Comment (arthurnn) [inline db/migrate/20160329184508_create_gem_download_count_index.rb]: > But since count will be changing a lot, the index will be changing a lot. And potentially render the table statistics invalid. So the index would not be very effective, and the data page hit may actually be quicker than dealing with a stale index.

That might change every 5 minutes. and only for gems that gets downloaded a lot. So I think the index is good in that case.

> The count column may slow down updates as well.

Yeah, that happens in a job, so it is fine.

> version_id is almost always be 0 - which is not good at the front of an index. Putting values that are the most different at the front makes for better data distribution

I want if this index, be able to look-up things by version_id only too. So thats why I added in the beginning. As far as i understand, there will be big branch on the b-tree index for the version_id = 0 , however the rest of the index will be balanced, as the second item is rubygem_id

**Comment by dwradcliffe** [comment]
:+1:

**Comment by kbrock** [comment]
Well, thanks for listening.
These changes look great

**Comment by arthurnn** [comment]
@kbrock thanks a lot for the suggestions. I will ping you in chat, to discuss more about theses indexes. I am used to Mysql, so I dont know much about `indexes where` types. Lets definitely talk.

❤️
