### PR TITLE
Have Pusher verify all certificates in a signed gem's cert_chain

### LINKED ISSUE #2830: Pusher accepts signed gems having a valid signing certificate and an expired root certificate
https://github.com/rubygems/rubygems.org/pull/2444 added signature verification to signed gems, but only against the signing (i.e. leaf) certificate.  If the cert chain contains more than one certificate, any of the root and/or intermediate certs may be expired or otherwise invalid. See [`Pusher`](https://github.com/rubygems/rubygems.org/blob/f84c2e741e233a55a2e3ac0f2f96c9fb2f7a1913/app/models/pusher.rb#L161) and [`LowSecurityPolicy`](https://github.com/rubygems/rubygems/blob/2f48d60afe050862258212d0c68530f39fb5fdfa/lib/rubygems/security/policies.rb#L46-L47).

## Steps to Reproduce
Let's create a signed gem with a valid signing certificate, `child_cert.pem`. This cert has been signed with an old CA certificate, `expired_root_cert.pem`.  We then push the gem and check the response.

1. Copy these test fixtures from rubygems:
  - [child_cert.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/child_cert.pem) - signing certificate
  - [child_key.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/child_key.pem) - private key for signing certificate
  - [expired_cert.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/expired_cert.pem) - root certificate
  - [private_key.pem](https://github.com/rubygems/rubygems/blob/master/test/rubygems/private_key.pem) - private key for root certificate, used to sign child_cert.pem
2. Sign your signing certificate:
```
gem cert -K private_key.pem -C expired_cert.pem --sign child_cert.pem
```
3. Add these two certs to the `cert_chain` of a gemspec, along with the child_key.pem as the `signing_key`. Here is an example:
```ruby
# ./expired_root_cert-0.0.0.gemspec
Gem::Specification.new do |s|
  s.name          = "expired_root_cert"
  s.version       = "0.0.0"
  s.platform      = "ruby"
  s.require_paths = ["lib"]
  s.authors       = ["Anthony The Tiger"]
  s.summary       = "A very bar gem"
  s.signing_key   = "child_key.pem"
  s.cert_chain    = ["expired_cert.pem","child_cert.pem"]
end
```
4. Build the gem.  **I had to modify my local `rubygems`' [`SigningPolicy`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/security/policies.rb#L98) by setting `verify_root = false`**, otherwise I can't create a new signed gem with an expired entry in the chain.  Pretend that the gem was generated at a point in time where all certs were valid.
```
ruby -Icustom/rubygems/lib custom/rubygems/bin/gem build expired_root_cert-0.0.0.gemspec
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  no homepage specified
WARNING:  no files specified
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: expired_root_cert
  Version: 0.0.0
  File: expired_root_cert-0.0.0.gem
```
5. Push `expired_root_cert-0.0.0.gem` to your local rubygems.org
```
RUBYGEMS_HOST=http://localhost:3000 gem push expired_root_cert-0.0.0.gem
Pushing gem to http://localhost:3000...
Successfully registered gem: expired_root_cert (0.0.0)
```
6. Try to install this gem locally with a MediumSecurity policy or higher:
```
gem install expired_root_cert-0.0.0.gem  -P MediumSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=nobody/DC=example not valid after 1970-01-01 00:00:00 UTC
```
So the server accepts this gem but the client rightfully rejects it.

## Expected Behavior
On step 5, we should get an response similar to what we see in Step 6:
```
RUBYGEMS_HOST=http://localhost:3000 gem push expired_root_cert-0.0.0.gem
Pushing gem to http://localhost:3000...
RubyGems.org cannot process this gem.
Please try rebuilding it and installing it locally to make sure it's valid.
Error:
certificate /CN=nobody/DC=example not valid after 1970-01-01 00:00:00 UTC
```

## Current Behavior
See Step 5.

## Possible Solution
Don't use LowSecurity in Pusher when vetting a signed gem.  Don't use MediumSecurity either, as that one requires the root cert in the chain to be in the trust store.  None of the predefined policies in `rubygems/security/policies.rb` really do what we want.

Let's instantiate a custom Policy for the duration of the push operation:
```ruby
  def gem_security_policy
    @gem_security_policy ||= begin
      # Verify that the gem signatures match the certificate chain (if present)
      policy = Gem::Security::Policy.new(
        'Pushing Policy',
        :verify_data      => true,
        :verify_signer    => true,
        :verify_chain     => true,
        :verify_root      => true,
        :only_trusted     => false,
        :only_signed      => false
      )
      # Silence warnings from the verification
      stream = StringIO.new
      policy.ui = Gem::StreamUI.new(stream, stream, stream, false)
      policy
    end
  end
```
**Spoiler alert!: Expect a PR doing just that soon. Also, the main protagonist was dead all along.**

## Environment
Browser and its version: Chrome Version 94.0.4606.81 (Official Build) (x86_64)
RubyGems version: 3.2.20
Ruby version: 2.7.4

### PR DESCRIPTION
**Pull request by rochlefebvre**
Fixes #2830 

This change implements the recommended fix from #2830's description.  Note that this policy will also reject root/intermediate certificates that have bad signatures, or are otherwise deemed invalid by Gem::Security::Policy.

## 🎩 
```
RUBYGEMS_HOST=http://localhost:3000 gem push expired_root_cert-0.0.0.gemPushing gem to http://localhost:3000...
RubyGems.org cannot process this gem.
Please try rebuilding it and installing it locally to make sure it's valid.
Error:
certificate /CN=nobody/DC=example not valid after 1970-01-01 00:00:00 UTC
```

### CODE REVIEW

File: app/models/pusher.rb [hunk 1]
```diff
@@ -158,7 +158,15 @@ def notify_unauthorized
   def gem_security_policy
     @gem_security_policy ||= begin
       # Verify that the gem signatures match the certificate chain (if present)
-      policy = Gem::Security::LowSecurity.dup
+      policy = Gem::Security::Policy.new(
```
Comment (simi) [inline app/models/pusher.rb:161]: Can we move this somewhere outside of this method into PushPolicy? :thinking: into model maybe?

Comment (rochlefebvre) [reply app/models/pusher.rb:161]: Good idea, I can define such a class under `app/models`.  I plan on also defining a PushPolicy in rubygems' `policies.rb` file, as suggested [here](https://github.com/rubygems/rubygems.org/issues/2830#issuecomment-951965495).  In the future, once rubygems.org moves to a rubygems having that constant, we can remove `app/models/push_policy.rb`.

What do you think?

File: app/models/push_policy.rb [hunk 2]
```diff
@@ -0,0 +1,9 @@
+PushPolicy = Gem::Security::Policy.new(
```
Comment (rochlefebvre) [inline app/models/push_policy.rb:1]: I chose not to define PushPolicy under the Gem::Security namespace because nothing else has that scope.  If rubygems winds up defining a Gem::Security::PushPolicy, then we can remove this one and switch to theirs.

**Review by simi — APPROVED** [review]
If I understand it well, this is related only to newly pushed gems and it prevents of pushing gems with wrong certificate in the chain. 

_This was problem for example recently for new LE authority on older systems if I remember well, since not all parts of the chain were valid for certificates._

**Review by sonalkr132 — APPROVED** [review]

**Comment by sonalkr132** [comment]
Thank you for working on this :100:
