### PR TITLE
Set info checksum in after version write job

### LINKED ISSUE #4331: Newly Pushed Gem Versions Cannot Be Resolved in Certain Cases
## Steps to Reproduce

1. A gem exists that hasn't been updated since the last monthly version file update
2. Install that gem in a project using `bundler`
3. Push a new version of that gem
4. Update the `gemfile` to require the new version of the gem
5. Run `bundle install`

## Expected Behavior

- The versions file includes the new version with an updated "info checksum"
- The new version of the gem is found and installed

## Current Behavior

- The versions file includes the new version but still has the previous "info checksum"
- Bundler's local cache of the gem's info is not updated, and the new version cannot be installed.

## Possible Solution
I think this is related to the following PR: https://github.com/rubygems/rubygems.org/pull/4255. 

I believe it's specifically related to this change
https://github.com/rubygems/rubygems.org/pull/4255/files#diff-61977d248b654178763e77a2fddc09152a20b85b1aecfc8222ef4233564593fcL269

and this, which is used to gather all the versions to generate the "info checksum":
https://github.com/rubygems/rubygems.org/blob/c204f62b560b263239d8cb196a331b3ea96b4463/app/models/gem_info.rb#L126

That the query is looking for `indexed = true`, but with the changes in the above PR that I linked to, that indexed value isn't being set until later.

If you look at this code block, that indexed attribute use to be set true on line 164, but now it's not set until the `AfterVersionWriteJob` executes. However, the query looking for index=true executes on line 182:
https://github.com/rubygems/rubygems.org/blob/c204f62b560b263239d8cb196a331b3ea96b4463/app/models/pusher.rb#L164-L182

### PR DESCRIPTION
**Pull request by segiddins**
This way, the info checksum is being set based upon the newly pushed version being indexed.

Fixes #4331

### CODE REVIEW

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
FYI @evman182

**Comment by simi** [comment]
Would it be possible to add test covering https://github.com/rubygems/rubygems.org/issues/4331 problem to ensure we're not going to repeat similar problem in the future?

File: test/integration/push_test.rb [hunk 1]
```diff
@@ -27,6 +27,11 @@ class PushTest < ActionDispatch::IntegrationTest
     css = %(div.gem__users a[alt=#{@user.handle}])
 
     assert page.has_css?(css, count: 2)
+
+    assert_equal Digest::MD5.hexdigest(<<~INFO), Rubygem.find_by!(name: "sandworm").versions.sole.info_checksum
```
Comment (segiddins) [inline test/integration/push_test.rb:31]: @simi doesn't this cover the issue? before it was different here, since the info checksum reflected an empty info file

**Review by indirect — APPROVED** [review]
Since we are still seeing info file problems, let's get this merged and plan to develop more specific tests if we see issues around info files in the future.
