### PR TITLE
Persist records before uploading to s3

### LINKED ISSUE #1551: Mismatched checksums on a couple gems
From https://github.com/bundler/bundler/issues/5332

Since Bundler 1.14 started validating checksums, a couple of people have had failed builds caused by seemingly invalid checksums in the RubyGems DB.

| gem | rubygems says | `shasum` says |
|-----|------|-----|
| faraday_middleware | c56bb3661af1d5057e578d72d2f9e93ab52630b74ebe37ce1118c93a6ddff56b | ff2bdbb6bdd5b2293f8ce7cb93572318dd068506e12f987f04a65209a2bc69cb
| azure-core | b04f7f994e3abc31003139a7ff8a682980c1d064a906a3290d5c369685bc478b  | 68ebac6994412a775584478961747a215d0844737a8b9a91405a0ac77fe6c514

@chrismo ran a check on the 700 most popular gems and didn't find any other instances, but that doesn't mean they aren't out there! It would be nice to know how these SHAs ended up this way.

### LINKED ISSUE #1564: race condition can lead to double gem push
Under certain circumstances, a gem with the same version can be pushed twice and results in 2 uploads to s3. This will cause the SHA to not match.

**This is ONLY possible from authenticated owners of the gem, not from malicious users.**

This happened recently from the `mailgun-ruby` gem version `1.1.3`.

I'll fill in more details shortly.

https://app.honeybadger.io/projects/40972/faults/32501071

s3 management console 2017-02-07 16-22-41

cc: @pixeltrix since you helped debug

### PR DESCRIPTION
**Pull request by sonalkr132**
When same gem version is pushed in parallel, upload to s3 is run for both the process. Process which commits transaction in Rubygems#update_attributes_from_gem_specification! first gets to set version.sha256, while process which uploads to s3 last gets to write gem file. These two processes need not be same and hence lead of sha mismatch.
If we persist version record before uploading to s3, other processes will get record not unique violation and not overwrite gem file in s3.

[Failing test on master](https://travis-ci.org/sonalkr132/rubygems.org/jobs/376936366#L1309).
Fixes #1564
Fixes #1551

### CODE REVIEW

File: test/unit/parallel_pusher_test.rb [hunk 1]
```diff
@@ -0,0 +1,43 @@
+require 'test_helper'
+
+class ParallelPusherTest < ActiveSupport::TestCase
+  self.use_transactional_tests = false
```
Comment (sonalkr132) [inline test/unit/parallel_pusher_test.rb]: This needs to be here because general test flow doesn't clear records created in `Thread.new` which use different db connection.

File: test/unit/parallel_pusher_test.rb [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+      GemDownload.delete_all
+    end
+
+    should "not lead to sha mismatch between gem file and db" do
+      @gem1 = gem_file("hola-0.0.0.gem")
+      @gem2 = gem_file("hola/hola-0.0.0.gem")
+      @cutter1 = Pusher.new(@user, @gem1)
+      @cutter2 = Pusher.new(@user, @gem2)
+
+      t1 = Thread.new do
```
Comment (simi) [inline test/unit/parallel_pusher_test.rb]: Isn't this threading introducing random order of execution of gem processing making this test "unstable"? Isn't there any chance to use `ActiveSupport Latch` to control the order?

Comment (sonalkr132) [reply test/unit/parallel_pusher_test.rb]: yes, it would definitely make it better. Thanks @simi 
`ActiveSupport::Concurrency::Latch` was deprecated in 5.1 and was replaced by `[Concurrent::CountDownLatch](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/CountDownLatch.html)` https://github.com/rails/rails/pull/20866. I have updated test to use the same.

**Comment by sonalkr132** [comment]
An alternate and perhaps more elegant approach to solving this would have been distributed lock. We would have to use [redis](https://redis.io/topics/distlock) or zookeeper and I don't think we are adding those dependencies. People seem to have [use memcache](https://github.com/nickelser/suo) (which we already use) for it as well but memache isn't really meant for it.

**Comment by indirect** [comment]
I think it would be fine to pair this with a cron job that checks recent gem versions to see if the file is actually on s3. then if the file is not on s3, delete the version row, so the user can try again?

**Comment by sonalkr132** [comment]
> a cron job that checks recent gem versions to see if the file is actually on s3

I don't think we need it. `Pusher#save` destroys the version if push to s3 failed. `version.destroy` in `rescue` was added (https://github.com/rubygems/rubygems.org/commit/87312bcfa5b1b5cef932caae0c90f2cfe9d4e4a2) in good faith but before this PR it was a dud. I have added a [test](https://github.com/rubygems/rubygems.org/pull/1723/files#diff-c6b58cc14a0325b136372c435b9e89dcR355) to ensure verison is deleted if upload to s3 fails.
If there is some other way, we can end with empty s3 object then let me know.

File: test/unit/parallel_pusher_test.rb (hunk 2 above)
Comment (simi) [reply test/unit/parallel_pusher_test.rb]: I don't see any difference with current code and the old one (using thread join). I think you should be able to use `Latch` to stop thread 1 somewhere, start thread 2 and continue in thread 1 to simulate the exact order of critical operations resulting in race condition at some points (which is the reason of this PR). Maybe I'm wrong. I try to submit my code to compare if welcomed.

Comment (sonalkr132) [reply test/unit/parallel_pusher_test.rb]: >  I try to submit my code to compare if welcomed.

Yes, please :pray: Even an example code of what you are trying to say would be fine as well.
I didn't even know about `ActiveSupport::Concurrency::Latch` until you mentioned it.

**Comment by indirect** [comment]
I'm very happy that this includes a test that exercises the "two simultaneous pushes" code path. Thanks for working on this!

@bundlerbot r+
