### PR TITLE
Return the latest version on search

### LINKED ISSUE #1249: ruby-prof is stuck at "0.8.1" in search results; 0.15.9 in its dedicated page
The search results for the query `ruby-prof` (<https://rubygems.org/search?utf8=%E2%9C%93&query=ruby-prof>) incorrectly say that the current version of that gem is `0.8.1`, see the screenshot at the end of this issue.

The current version of the `ruby-prof` gem is `0.15.9` and this is what is correctly shown in its dedicated page (<https://rubygems.org/gems/ruby-prof>).

Stale version info cached somewhere?

ruby-prof-0 8 1

### PR DESCRIPTION
**Pull request by arthurnn**
On latest_version association, we need to order by the latest created at, otherwise
we can have more than one version maked as latest=true, because we mark those based on
the platforms. Thus the same rubygem has more than one `latest=true` version.
However, the association, should return only the latest version, so we need to order.

[fixes #1249]

review @dwradcliffe @gioele

Tested this locally, and it works.

### CODE REVIEW

File: app/models/rubygem.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ class Rubygem < ActiveRecord::Base
   has_many :subscribers, through: :subscriptions, source: :user
   has_many :subscriptions, dependent: :destroy
   has_many :versions, dependent: :destroy, validate: false
-  has_one :latest_version, -> { where(latest: true) }, class_name: "Version"
+  has_one :latest_version, -> { where(latest: true).order(created_at: :desc) }, class_name: "Version"
```
Comment (simi) [inline app/models/rubygem.rb]: Does that order mean when I'll push version `2.1` and after I'll push `1.2` version with some backport for example, `1.2` will be the latest version?

Comment (arthurnn) [inline app/models/rubygem.rb]: Yeah. I think the latest version pushed in the system should be the one showing on the grid/index. That was the behaviour before too, as far as I can tell. 
Good question.

**Comment by arthurnn** [comment]
@dwradcliffe thoughts?

File: app/models/rubygem.rb (hunk 1 above)
Comment (dwradcliffe) [inline app/models/rubygem.rb]: Only if they were different platforms. There is only one latest: true per platform.

**Comment by dwradcliffe** [comment]
LGTM
