### PR TITLE
fixes rubygem blank documentation url

### LINKED ISSUE #967: documentation_uri missing from the api
This issue is similar to #952.

The `ftpd` gem has documentation listed on its page:
https://rubygems.org/gems/ftpd

However, the API does not return it:
```sh
> curl https://rubygems.org/api/v1/gems/ftpd.json
{"name":"ftpd","downloads":27993,"version":"1.1.1","version_downloads":1521,"platform":"ruby","authors":"Wayne Conrad","info":"ftpd is a pure Ruby FTP server library.  It supports implicit and explicit TLS, IPV6, passive and active mode, and is unconditionally compliant per RFC-1123.  It can be used as part of a test fixture or embedded in a program.","licenses":["MIT"],"metadata":{},"sha":"b4644c29cf8ecc1e516c13b00d432a0846b2f7da1d95429cdd59a1970e39f2f4","project_uri":"http://rubygems.org/gems/ftpd","gem_uri":"http://rubygems.org/gems/ftpd-1.1.1.gem","homepage_uri":"http://github.com/wconrad/ftpd","wiki_uri":"https://github.com/wconrad/ftpd/wiki","documentation_uri":"","mailing_list_uri":"","source_code_uri":"https://github.com/wconrad/ftpd","bug_tracker_uri":"https://github.com/wconrad/ftpd/issues","dependencies":{"development":[{"name":"cucumber","requirements":"~\u003e 1.3"},{"name":"double-bag-ftps","requirements":"~\u003e 0.1"},{"name":"jeweler","requirements":"~\u003e 2.0"},{"name":"rake","requirements":"~\u003e 10.3"},{"name":"redcarpet","requirements":"~\u003e 3.1"},{"name":"rspec","requirements":"~\u003e 3.1"},{"name":"rspec-its","requirements":"~\u003e 1.0"},{"name":"timecop","requirements":"~\u003e 0.7"},{"name":"yard","requirements":"~\u003e 0.8.7"}],"runtime":[{"name":"memoizer","requirements":"~\u003e 1.0"}]}}%
```

Unlike the previous case the documentation is `""` rather than `nil`.

### PR DESCRIPTION
**Pull request by farukaydin**
fixes #967

@AaronLasseigne I think it solves your problem cc // @sferik

### CODE REVIEW

**Comment by arthurnn** [comment]
Can you write a test case to cover the issue?

**Comment by sferik** [comment]
Why is this necessary for docs but none of the other linkset items? I would rather fix this problem at the source, if that’s possible.

**Comment by farukaydin** [comment]
@sferik we assign default docs link if user doesn't provide any docs link for the gem. Also we return this default link through api responses. But when user edit the gem links, let say edit the wiki and homepage urls and leave blank the docs url, docs url will be empty string and thus payload method return
```linkset.try(:docs)``` without looking ```version.documentation_path``` because of empty string. Other linkset items have no default values, thats why we encounter this problem for only docs link.

If this solution is not as good as we want, maybe we can override docs getter and check the situation at the model level.

**Comment by arthurnn** [comment]
I think this solution make sense.. As we need to check the `presence` only for the link that we try to fallback to another thing if the first dont exist.
We just need a test, and I will merge this.

**Comment by farukaydin** [comment]
@arthurnn I added the test and rebased it.

File: test/unit/rubygem_test.rb [hunk 1]
```diff
@@ -388,6 +388,14 @@ class RubygemTest < ActiveSupport::TestCase
         assert_equal @rubygem.linkset.bugs, hash["bug_tracker_uri"]
       end
 
+      should "return version documentation url if linkset docs is empty" do
+        @rubygem.linkset.docs = ""
+        @rubygem.save
+        hash = MultiJson.load(@rubygem.to_json)
```
Comment (arthurnn) [inline test/unit/rubygem_test.rb]: Can you just use `JSON` class here instead of `MultiJson`?
I am pretty much sure, we are trying to remove that dependency.

File: test/unit/rubygem_test.rb [hunk 2]
```diff
@@ -374,7 +374,7 @@ class RubygemTest < ActiveSupport::TestCase
     context "with a linkset" do
       setup do
         @rubygem = build(:rubygem)
-        version = create(:version, :rubygem => @rubygem)
+        @version = create(:version, :rubygem => @rubygem)
```
Comment (arthurnn) [inline test/unit/rubygem_test.rb]: as you are here, do you mind updating this line to new hash syntax.

**Comment by farukaydin** [comment]
@arthurnn I fixed both of them, btw thanks for quick review.

**Comment by arthurnn** [comment]
I am running a bid migration in production right now. to populate the metadata from the specs. After those are done I will merge this and deploy.

thanks
